### ISSUE TITLE
Parsing  icoming message

### ISSUE THREAD

**Issue by Netz00** [Netz00/ES8266-full-duplex-RC#2]
Make code for parsing 5 substrings from message, with **&** as a delimiter. 

`XXXX&XXXX&XXXX&XXXX&XXXX\0`

`voltage at cell` 1 & `voltage at cell `2 & `current load` & `parking sensor distance` & `RSSI`

Example:
Input: `3.8&3.936&6.936&50.32&76`
Output: [`3.8`, `3.936`, `6.936`, `50.32`, `76`]

**Comment by dorabor** [comment]
` @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        final Handler handler = new Handler();
        final AlertDialog.Builder builder = new AlertDialog.Builder(this);

        String[] msg = parseString("DORA&BORIC&BOZO&DURDOV&FESB");
        builder.setMessage(msg[1]);
        final AlertDialog dialog = builder.create();
        dialog.show();
    }


    public String[] parseString(String str) {
        return str.split("[&]");
    }`
